window.TRIP_DATA = {
  "generatedFrom": "eastern_townships_activities_v3.md",
  "categories": [
    {
      "id": "breweries",
      "label": "Breweries",
      "color": "#d97706",
      "icon": "B",
      "count": 14
    },
    {
      "id": "vineyards",
      "label": "Vineyards",
      "color": "#9d174d",
      "icon": "V",
      "count": 13
    },
    {
      "id": "bike",
      "label": "Bike loops",
      "color": "#2563eb",
      "icon": "R",
      "count": 18
    },
    {
      "id": "beaches",
      "label": "Beaches",
      "color": "#0891b2",
      "icon": "S",
      "count": 13
    },
    {
      "id": "cafes",
      "label": "Cafés",
      "color": "#7c3f10",
      "icon": "C",
      "count": 18
    },
    {
      "id": "dining",
      "label": "Dining",
      "color": "#15803d",
      "icon": "D",
      "count": 6
    },
    {
      "id": "villages",
      "label": "Villages",
      "color": "#6d28d9",
      "icon": "T",
      "count": 8
    },
    {
      "id": "scenic",
      "label": "Scenic drives",
      "color": "#ea580c",
      "icon": "W",
      "count": 3
    },
    {
      "id": "experiences",
      "label": "Experiences",
      "color": "#475569",
      "icon": "E",
      "count": 4
    }
  ],
  "places": [
    {
      "id": "breweries-brasserie-dunham-dunham-maps",
      "title": "Brasserie Dunham (Dunham)",
      "baseTitle": "Brasserie Dunham (Dunham)",
      "category": "breweries",
      "section": "Rustic Breweries (Microbrasseries)",
      "subsection": "",
      "description": "Small craft brewery in Dunham known for IPAs such as Cyclope IPA, Saison du Pinacle and Viti Vini Vici. The PDF listing of microbreweries notes that nearby stops include L’Épicerie‑Café Dunham and the Gagliano vineyard.",
      "lat": 45.1304167,
      "lng": -72.8001991,
      "mapsUrl": "https://www.google.com/maps?cid=4061911242529537363",
      "routeUrl": null,
      "rating": null,
      "resolvedName": "Brasserie Dunham / Pub & Boutique",
      "address": "3809 Rue Principale, Dunham, QC J0E 1M0",
      "status": null,
      "linkLabel": "Maps"
    },
    {
      "id": "breweries-lautre-brasserie-bedford-maps",
      "title": "L’Autre Brasserie (Bedford)",
      "baseTitle": "L’Autre Brasserie (Bedford)",
      "category": "breweries",
      "section": "Rustic Breweries (Microbrasseries)",
      "subsection": "",
      "description": "Microbrewery at 110 rue de la Rivière with beers like P’tite Grisette and La Blonde de l’Autre; nearby attractions include Comptoir Moutarde delicatessen, Fromagerie Missiska, Vignoble L’Ardennais and the Beat & Betterave nanobrasserie.",
      "lat": 45.1191737,
      "lng": -72.9797882,
      "mapsUrl": "https://www.google.com/maps?cid=6048336917458768197",
      "routeUrl": null,
      "rating": null,
      "resolvedName": "L'Autre Brasserie",
      "address": "110 Rue Rivière Local 106, Bedford, Quebec J0J 1A0",
      "status": null,
      "linkLabel": "Maps"
    },
    {
      "id": "breweries-farnham-ale-lager-farnham-maps",
      "title": "Farnham Ale & Lager (Farnham)",
      "baseTitle": "Farnham Ale & Lager (Farnham)",
      "category": "breweries",
      "section": "Rustic Breweries (Microbrasseries)",
      "subsection": "",
      "description": "Brewpub producing a range of lagers and ales—27 Lager blonde, 35 Red English and 12 German wheat. The brewery is close to Fromagerie des Cantons, Vignoble de la Bauge and the Montérégiade cycle path.",
      "lat": 45.2848506,
      "lng": -72.9888541,
      "mapsUrl": "https://www.google.com/maps?cid=12250271170320761753",
      "routeUrl": null,
      "rating": null,
      "resolvedName": "Farnham Ale & Lager",
      "address": "401 Boul de Normandie N, Farnham, QC J2N 1W5",
      "status": null,
      "linkLabel": "Maps"
    },
    {
      "id": "breweries-nanobrasserie-beat-betterave-frelighsburg-maps",
      "title": "Nanobrasserie Beat & Betterave (Frelighsburg)",
      "baseTitle": "Nanobrasserie Beat & Betterave (Frelighsburg)",
      "category": "breweries",
      "section": "Rustic Breweries (Microbrasseries)",
      "subsection": "",
      "description": "This small brewery and café hosts concerts and offers beers such as the rye‑flavoured Agent 00 and the stout Matière Sombre. It is dog‑friendly, accessible and close to Boulangerie La Mie Bretonne and Domaine du P’tit Bonheur vineyard.",
      "lat": 45.0536045,
      "lng": -72.8386602,
      "mapsUrl": "https://www.google.com/maps?cid=4567539654388329645",
      "routeUrl": null,
      "rating": null,
      "resolvedName": "Beat & Betterave - Nanobrasserie & Café",
      "address": "41 Rue Principale, Frelighsburg, QC J0J 1C0",
      "status": null,
      "linkLabel": "Maps"
    },
    {
      "id": "breweries-le-sage-brasseur-cowansville-maps",
      "title": "Le Sage Brasseur (Cowansville)",
      "baseTitle": "Le Sage Brasseur (Cowansville)",
      "category": "breweries",
      "section": "Rustic Breweries (Microbrasseries)",
      "subsection": "",
      "description": "Brewery known for raspberry‑honey beer and maple red ale; located in Cowansville near attractions such as the Musée du chocolat de la Confiserie Bromont and Domaine ValBrome vineyard.",
      "lat": 45.1991364,
      "lng": -72.7492041,
      "mapsUrl": "https://www.google.com/maps?cid=2340603723432744437",
      "routeUrl": null,
      "rating": null,
      "resolvedName": "Le Sage Brasseur - Microbrasserie Artisanale",
      "address": "1000 Rue du Sud, Cowansville, QC J2K 2Y3",
      "status": null,
      "linkLabel": "Maps"
    },
    {
      "id": "breweries-micro-brasserie-le-brouemont-bromont-maps",
      "title": "Micro‑brasserie le Brouemont (Bromont)",
      "baseTitle": "Micro‑brasserie le Brouemont (Bromont)",
      "category": "breweries",
      "section": "Rustic Breweries (Microbrasseries)",
      "subsection": "",
      "description": "Produces Golden Ale, stout and the Feu de joie NEIPA. Visitors can combine a visit with nearby vineyards such as Vignoble Bromont and Léon Courville.",
      "lat": 45.3157143,
      "lng": -72.642442,
      "mapsUrl": "https://www.google.com/maps?cid=2338048253867737505",
      "routeUrl": null,
      "rating": null,
      "resolvedName": "Brouemont - Microbrasserie & Restaurant",
      "address": "107 Bd de Bromont, Bromont, QC J2L 2K7",
      "status": null,
      "linkLabel": "Maps"
    },
    {
      "id": "breweries-microbrasserie-coaticook-coaticook-maps",
      "title": "Microbrasserie Coaticook (Coaticook)",
      "baseTitle": "Microbrasserie Coaticook (Coaticook)",
      "category": "breweries",
      "section": "Rustic Breweries (Microbrasseries)",
      "subsection": "",
      "description": "Craft brewery with a restaurant and terrace; the tourism page notes that the beers are authentic, balanced and ideal after outdoor activities.",
      "lat": 45.156984,
      "lng": -71.8003513,
      "mapsUrl": "https://www.google.com/maps?cid=5575577621459429975",
      "routeUrl": null,
      "rating": null,
      "resolvedName": "Microbrasserie Coaticook",
      "address": "1007 Rue Child, Coaticook, QC J1A 2S5",
      "status": null,
      "linkLabel": "Maps"
    },
    {
      "id": "breweries-hop-station-coaticook-maps",
      "title": "Hop Station (Coaticook)",
      "baseTitle": "Hop Station (Coaticook)",
      "category": "breweries",
      "section": "Rustic Breweries (Microbrasseries)",
      "subsection": "",
      "description": "Dynamic microbrewery located in the town’s old train station; offers original beers and a large cocktail menu. The Mexican‑inspired kitchen uses fresh house‑made products.",
      "lat": 45.1311276,
      "lng": -71.8086811,
      "mapsUrl": "https://www.google.com/maps?cid=17366708758363039196",
      "routeUrl": null,
      "rating": null,
      "resolvedName": "Hop Station - Microbrasserie",
      "address": "131 Rue Lovell, Coaticook, QC J1A 3B2",
      "status": null,
      "linkLabel": "Maps"
    },
    {
      "id": "breweries-siboire-jacques-cartier-sherbrooke-maps",
      "title": "Siboire Jacques‑Cartier (Sherbrooke)",
      "baseTitle": "Siboire Jacques‑Cartier (Sherbrooke)",
      "category": "breweries",
      "section": "Rustic Breweries (Microbrasseries)",
      "subsection": "",
      "description": "Microbrewery and restaurant overlooking Lac‑des‑Nations; guests can enjoy lunch or dinner and fill beer jugs to take home.",
      "lat": 45.3979548,
      "lng": -71.918378,
      "mapsUrl": "https://www.google.com/maps?cid=16342521361991137381",
      "routeUrl": null,
      "rating": null,
      "resolvedName": "Siboire Jacques-Cartier",
      "address": "40 Boulevard Jacques-Cartier S, Sherbrooke, QC J1J 2Z2",
      "status": null,
      "linkLabel": "Maps"
    },
    {
      "id": "breweries-la-mare-au-diable-sherbrooke-maps",
      "title": "La Mare au Diable (Sherbrooke)",
      "baseTitle": "La Mare au Diable (Sherbrooke)",
      "category": "breweries",
      "section": "Rustic Breweries (Microbrasseries)",
      "subsection": "",
      "description": "Sherbrooke’s oldest microbrewery with a warm interior and large terrace; serves its own beers and boasts one of Québec’s largest whisky selections.",
      "lat": 45.4008933,
      "lng": -71.891652,
      "mapsUrl": "https://www.google.com/maps?cid=17388787336625209882",
      "routeUrl": null,
      "rating": null,
      "resolvedName": "La Mare au Diable - Microbrasserie",
      "address": "151 Rue King Ouest, Sherbrooke, QC J1H 1P4",
      "status": null,
      "linkLabel": "Maps"
    },
    {
      "id": "breweries-microbrasserie-de-la-cie-vilandre-north-hatley-maps",
      "title": "Microbrasserie de la Cie Vilandré (North Hatley)",
      "baseTitle": "Microbrasserie de la Cie Vilandré (North Hatley)",
      "category": "breweries",
      "section": "Rustic Breweries (Microbrasseries)",
      "subsection": "",
      "description": "Offers a broad range of beers on tap—20 products—from a terrace overlooking the Massawippi River.",
      "lat": 45.2764675,
      "lng": -71.9726697,
      "mapsUrl": "https://www.google.com/maps?cid=13389393403950541544",
      "routeUrl": null,
      "rating": null,
      "resolvedName": "Microbrasserie de La Cie Vilandré",
      "address": "220 Rue Ml, North Hatley, Quebec J0B 2C0",
      "status": null,
      "linkLabel": "Maps"
    },
    {
      "id": "breweries-microbrasserie-equinoxe-mansonville-potton-maps",
      "title": "Microbrasserie Équinoxe (Mansonville/Potton)",
      "baseTitle": "Microbrasserie Équinoxe (Mansonville/Potton)",
      "category": "breweries",
      "section": "Rustic Breweries (Microbrasseries)",
      "subsection": "",
      "description": "New microbrewery (2022) with pub meals during the day and Italian dinners at night; beers brewed on site and complemented by guest beers, wine and cocktails.",
      "lat": 45.0513812,
      "lng": -72.3918726,
      "mapsUrl": "https://www.google.com/maps?cid=2263860173809720485",
      "routeUrl": null,
      "rating": null,
      "resolvedName": "Équinoxe - Microbrasserie / Resto & BrouePub",
      "address": "304 Rue Principale, Mansonville, QC J0E 1X0",
      "status": null,
      "linkLabel": "Maps"
    },
    {
      "id": "breweries-la-confrerie-artisans-brasseurs-windsor-maps",
      "title": "La Confrérie Artisans Brasseurs (Windsor)",
      "baseTitle": "La Confrérie Artisans Brasseurs (Windsor)",
      "category": "breweries",
      "section": "Rustic Breweries (Microbrasseries)",
      "subsection": "",
      "description": "Family‑run microbrewery specialising in fruity beers made with local ingredients; features a tasting room overlooking the brewhouse and a large dog‑ and kid‑friendly terrace.",
      "lat": 45.5628054,
      "lng": -72.0191402,
      "mapsUrl": "https://www.google.com/maps?cid=3659859097623394105",
      "routeUrl": null,
      "rating": null,
      "resolvedName": "La Confrérie Artisans Brasseurs",
      "address": "1280 Rue Maurice-Bachand, Windsor, QC J1S 0J1",
      "status": null,
      "linkLabel": "Maps"
    },
    {
      "id": "breweries-lardoise-cooperative-brassicole-richmond-maps",
      "title": "L’Ardoise, coopérative brassicole (Richmond)",
      "baseTitle": "L’Ardoise, coopérative brassicole (Richmond)",
      "category": "breweries",
      "section": "Rustic Breweries (Microbrasseries)",
      "subsection": "",
      "description": "Cooperative microbrewery (opened 2021) offering a variety of beers and snacks in a relaxed atmosphere.",
      "lat": 45.6623066,
      "lng": -72.1437504,
      "mapsUrl": "https://www.google.com/maps?cid=8328499034882904781",
      "routeUrl": null,
      "rating": null,
      "resolvedName": "L'Ardoise - Coopérative Brassicole",
      "address": "445 Rue Principale Nord, Richmond, Quebec J0B 2H0",
      "status": null,
      "linkLabel": "Maps"
    },
    {
      "id": "vineyards-domaine-du-ridge-saint-armand-maps",
      "title": "Domaine du Ridge (Saint‑Armand)",
      "baseTitle": "Domaine du Ridge (Saint‑Armand)",
      "category": "vineyards",
      "section": "Vineyards & Cider Estates",
      "subsection": "",
      "description": "A key stop on the wine route; visitors taste wines crafted with care amid a picturesque vineyard. The estate’s Epicurean package introduces Quebec viticulture and finishes with local product tastings.",
      "lat": 45.0727262,
      "lng": -72.9349215,
      "mapsUrl": "https://www.google.com/maps?cid=8743919794417705986",
      "routeUrl": null,
      "rating": null,
      "resolvedName": "Domaine du Ridge",
      "address": "205 Chem. Ridge, Saint-Armand, QC J0J 1T0",
      "status": null,
      "linkLabel": "Maps"
    },
    {
      "id": "vineyards-chateau-ste-agnes-sutton-maps",
      "title": "Château Ste‑Agnès (Sutton)",
      "baseTitle": "Château Ste‑Agnès (Sutton)",
      "category": "vineyards",
      "section": "Vineyards & Cider Estates",
      "subsection": "",
      "description": "Historic estate with about 7,000 vines planted on terraces supported by stone walls. It offers breathtaking views of the Appalachian Mountains and produces wines ranging from white and rosé to orange, late‑harvest and fortified wines.",
      "lat": 45.0236244,
      "lng": -72.5832901,
      "mapsUrl": "https://www.google.com/maps?cid=1910645581862683610",
      "routeUrl": null,
      "rating": null,
      "resolvedName": "Château Ste-Agnès",
      "address": "2559 Chem. Scenic Road, Sutton, QC J0E 2K0",
      "status": null,
      "linkLabel": "Maps"
    },
    {
      "id": "vineyards-val-caudalies-dunham-maps",
      "title": "Val Caudalies (Dunham)",
      "baseTitle": "Val Caudalies (Dunham)",
      "category": "vineyards",
      "section": "Vineyards & Cider Estates",
      "subsection": "",
      "description": "Vineyard and cider estate producing award‑winning wines, vermouth and cider. The estate has panoramic views from its covered terrace; visitors can wander through orchards and vineyards, picnic and pick grapes or apples.",
      "lat": 45.0813522,
      "lng": -72.8185685,
      "mapsUrl": "https://www.google.com/maps?cid=11378741565905190397",
      "routeUrl": null,
      "rating": null,
      "resolvedName": "Val Caudalies - Vignoble & Cidrerie",
      "address": "4921 Rue Principale, Dunham, QC J0E 1M0",
      "status": null,
      "linkLabel": "Maps"
    },
    {
      "id": "vineyards-le-vignoble-du-ruisseau-dunham-maps",
      "title": "Le Vignoble du Ruisseau (Dunham)",
      "baseTitle": "Le Vignoble du Ruisseau (Dunham)",
      "category": "vineyards",
      "section": "Vineyards & Cider Estates",
      "subsection": "",
      "description": "Vineyard, distillery, cider mill and maple grove aiming for self‑sufficiency. Facilities include a covered bridge, vaulted barrel cellar, two‑level winery, outdoor tasting areas, cocktail bar and a bistro overlooking the creek.",
      "lat": 45.0992042,
      "lng": -72.7114177,
      "mapsUrl": "https://www.google.com/maps?cid=11711557137074462202",
      "routeUrl": null,
      "rating": null,
      "resolvedName": "Le Vignoble du Ruisseau - Winery & Cidery",
      "address": "4500 Chem. Strobl, Dunham, QC J0E 1M0",
      "status": null,
      "linkLabel": "Maps"
    },
    {
      "id": "vineyards-vignoble-gagliano-dunham-maps",
      "title": "Vignoble Gagliano (Dunham)",
      "baseTitle": "Vignoble Gagliano (Dunham)",
      "category": "vineyards",
      "section": "Vineyards & Cider Estates",
      "subsection": "",
      "description": "Family‑run vineyard on the wine route where visitors can pair Italian‑inspired pizzas with wines; near Brasserie Dunham.",
      "lat": 45.1098014,
      "lng": -72.8562105,
      "mapsUrl": "https://www.google.com/maps?cid=1584203415565794011",
      "routeUrl": null,
      "rating": null,
      "resolvedName": "Vignoble Gagliano",
      "address": "1046 Rue Bruce, Dunham, QC J0E 1M0",
      "status": null,
      "linkLabel": "Maps"
    },
    {
      "id": "vineyards-vignoble-de-lorpailleur-dunham-maps",
      "title": "Vignoble de l’Orpailleur (Dunham)",
      "baseTitle": "Vignoble de l’Orpailleur (Dunham)",
      "category": "vineyards",
      "section": "Vineyards & Cider Estates",
      "subsection": "",
      "description": "Pioneering vineyard (planted 1982) noted for sparkling wines made using the traditional Champenoise method.",
      "lat": 45.1095737,
      "lng": -72.8590423,
      "mapsUrl": "https://www.google.com/maps?cid=17627055737384758073",
      "routeUrl": null,
      "rating": null,
      "resolvedName": "Vignoble de l’Orpailleur",
      "address": "1086 Rue Bruce, Dunham, QC J0E 1M0",
      "status": null,
      "linkLabel": "Maps"
    },
    {
      "id": "vineyards-la-halte-des-pelerins-sherbrooke-maps",
      "title": "La Halte des Pèlerins (Sherbrooke)",
      "baseTitle": "La Halte des Pèlerins (Sherbrooke)",
      "category": "vineyards",
      "section": "Vineyards & Cider Estates",
      "subsection": "",
      "description": "Urban vineyard near downtown Sherbrooke offering approachable wines and numerous activities. Google Maps currently marks it temporarily closed.",
      "lat": 45.4439187,
      "lng": -71.8903897,
      "mapsUrl": "https://www.google.com/maps?cid=5608194349998191423",
      "routeUrl": null,
      "rating": null,
      "resolvedName": "La Halte des Pèlerins",
      "address": "693 Chem. du Sanctuaire, Sherbrooke, QC J1H 0E1",
      "status": "Temporarily closed",
      "linkLabel": "Maps"
    },
    {
      "id": "vineyards-clos-saragnat-frelighsburg-maps",
      "title": "Clos Saragnat (Frelighsburg)",
      "baseTitle": "Clos Saragnat (Frelighsburg)",
      "category": "vineyards",
      "section": "Vineyards & Cider Estates",
      "subsection": "",
      "description": "Vineyard created by pioneer Christian Barthomeuf, famous for its sweet straw wine made from dried grapes. Google Maps currently marks it temporarily closed.",
      "lat": 45.0376641,
      "lng": -72.7934387,
      "mapsUrl": "https://www.google.com/maps?cid=3104163103148187406",
      "routeUrl": null,
      "rating": null,
      "resolvedName": "Clos Saragnat - Vins & Cidres",
      "address": "100 Chem. de Richford, Frelighsburg, QC J0J 1C0",
      "status": "Temporarily closed",
      "linkLabel": "Maps"
    },
    {
      "id": "vineyards-le-cep-dargent-magog-maps",
      "title": "Le Cep d’Argent (Magog)",
      "baseTitle": "Le Cep d’Argent (Magog)",
      "category": "vineyards",
      "section": "Vineyards & Cider Estates",
      "subsection": "",
      "description": "Producer of sparkling wines using the Champenoise method with an interpretation centre explaining the process.",
      "lat": 45.2912677,
      "lng": -72.0561697,
      "mapsUrl": "https://www.google.com/maps?cid=1743162334933700465",
      "routeUrl": null,
      "rating": null,
      "resolvedName": "Vignoble Le Cep d'Argent",
      "address": "1257 Chem. de la Rivière, Magog, QC J1X 3W5",
      "status": null,
      "linkLabel": "Maps"
    },
    {
      "id": "vineyards-domaine-bergeville-canton-de-hatley-maps",
      "title": "Domaine Bergeville (Canton de Hatley)",
      "baseTitle": "Domaine Bergeville (Canton de Hatley)",
      "category": "vineyards",
      "section": "Vineyards & Cider Estates",
      "subsection": "",
      "description": "Only vineyard in Quebec devoted solely to sparkling wine using the traditional Brut method; emphasises environmental practices. Google Maps currently marks it temporarily closed.",
      "lat": 45.2727271,
      "lng": -71.9484994,
      "mapsUrl": "https://www.google.com/maps?cid=6248733240220878062",
      "routeUrl": null,
      "rating": null,
      "resolvedName": "Domaine Bergeville",
      "address": "1030 Chem. Sherbrooke, Hatley, QC J0B 2C0",
      "status": "Temporarily closed",
      "linkLabel": "Maps"
    },
    {
      "id": "vineyards-vignoble-de-la-bauge-brigham-maps",
      "title": "Vignoble de la Bauge (Brigham)",
      "baseTitle": "Vignoble de la Bauge (Brigham)",
      "category": "vineyards",
      "section": "Vineyards & Cider Estates",
      "subsection": "",
      "description": "Scenic vineyard featuring an exotic animal park; has produced organic wines since 2016.",
      "lat": 45.234658,
      "lng": -72.854751,
      "mapsUrl": "https://www.google.com/maps?cid=3636606575332782005",
      "routeUrl": null,
      "rating": null,
      "resolvedName": "Vignoble de la Bauge",
      "address": "155 Av. des Érables, Brigham, QC J2K 4E1",
      "status": null,
      "linkLabel": "Maps"
    },
    {
      "id": "vineyards-leon-courville-vigneron-lac-brome-knowlton-maps",
      "title": "Léon Courville Vigneron (Lac‑Brome/Knowlton)",
      "baseTitle": "Léon Courville Vigneron (Lac‑Brome/Knowlton)",
      "category": "vineyards",
      "section": "Vineyards & Cider Estates",
      "subsection": "",
      "description": "Vineyard overlooking Brome Lake, producing award‑winning wines and offering tastings on a terrace.",
      "lat": 45.262185,
      "lng": -72.58868,
      "mapsUrl": "https://www.google.com/maps?cid=6180641580424069284",
      "routeUrl": null,
      "rating": null,
      "resolvedName": "Domaine Les Brome / Léon Courville, winemaker",
      "address": "285 Chem. Brome, Fulford, QC J0E 1S0",
      "status": null,
      "linkLabel": "Maps"
    },
    {
      "id": "vineyards-vignoble-bromont-brigham-bromont-maps",
      "title": "Vignoble Bromont (Brigham/Bromont)",
      "baseTitle": "Vignoble Bromont (Brigham/Bromont)",
      "category": "vineyards",
      "section": "Vineyards & Cider Estates",
      "subsection": "",
      "description": "Vineyard with lodging and boutique; near micro‑brasserie Le Brouemont.",
      "lat": 45.253152,
      "lng": -72.735317,
      "mapsUrl": "https://www.google.com/maps?cid=11933346642509835799",
      "routeUrl": null,
      "rating": null,
      "resolvedName": "Vignoble Bromont Auberge & Boutique",
      "address": "1095 Chemin N, Brigham, QC J2K 0P6",
      "status": null,
      "linkLabel": "Maps"
    },
    {
      "id": "bike-circuit-du-patrimoine-bedford-map",
      "title": "Circuit du patrimoine (Bedford)",
      "baseTitle": "Circuit du patrimoine (Bedford)",
      "category": "bike",
      "section": "Bike Loops (50–80 km)",
      "subsection": "",
      "description": "≈ 42 km loop (38 km paved, 4 km unpaved). Visits Walbridge 12‑sided barn, Quebec’s smallest covered bridge and heritage homes in Mystic and Stanbridge East. Grab a cheese platter at Missiska cheese factory, explore the Missisquoi Museum, then taste wines at Domaine du Ridge or microbrews at L’Autre Brasserie. Ride with GPS example: ≈ 42.8 km, +177 m climbing, 6.8 % average grade; start location shown as Bedford, Quebec, with a Send to Device button.",
      "lat": 45.12,
      "lng": -72.984,
      "mapsUrl": "https://www.google.com/maps/search/?api=1&query=%C3%89glise+Saint-Damien+Bedford+rue+de+l+%C3%89glise+Quebec",
      "routeUrl": "https://www.easterntownships.org/cycling/circuit/5/circuit-du-patrimoine",
      "rating": 4,
      "resolvedName": null,
      "address": null,
      "status": null,
      "linkLabel": "Map"
    },
    {
      "id": "bike-magog-orford-magog-map",
      "title": "Magog‑Orford (Magog)",
      "baseTitle": "Magog‑Orford (Magog)",
      "category": "bike",
      "section": "Bike Loops (50–80 km)",
      "subsection": "",
      "description": "≈ 33 km circuit connecting Magog to Orford; mostly paved with stretches through Parc national du Mont‑Orford and postcard‑perfect villages. Stop at Chocolats Vanden Eynden, Vignoble d’Orford and microbreweries La Memphré and Canton Brasse. Enjoy a beer at La Memphré or Canton Brasse or stroll the Pointe‑Merry waterfront. Ride with GPS example: 33 km, +292 m elevation, 10.4 % average grade; created February 2020 and updated April 2020, with a Send to Device button.",
      "lat": 45.2674,
      "lng": -72.1461,
      "mapsUrl": "https://www.google.com/maps/search/?api=1&query=Parc+de+la+Pointe-Merry+Magog+Quebec",
      "routeUrl": "https://www.easterntownships.org/cycling/circuit/8/magog-orford",
      "rating": 4,
      "resolvedName": null,
      "address": null,
      "status": null,
      "linkLabel": "Map"
    },
    {
      "id": "bike-grand-tour-du-lac-megantic-lac-megantic-map",
      "title": "Grand tour du lac Mégantic (Lac Mégantic)",
      "baseTitle": "Grand tour du lac Mégantic (Lac Mégantic)",
      "category": "bike",
      "section": "Bike Loops (50–80 km)",
      "subsection": "",
      "description": "≈ 56 km loop around Lake Mégantic; combines shoreline views, wooded sections and some climbs. Reward yourself with a beer at La Gare’nison or relax at the Baie‑des‑Sables beach; visit Piopolis village for history and views. Ride with GPS example: ≈ 57.1 km, +525 m elevation gain, 6.5 % average grade; start location shown as Lac-Mégantic.",
      "lat": 45.5819,
      "lng": -70.8886,
      "mapsUrl": "https://www.google.com/maps/search/?api=1&query=Parc+des+V%C3%A9t%C3%A9rans+Lac-M%C3%A9gantic+Quebec",
      "routeUrl": "https://www.easterntownships.org/cycling/circuit/21/grand-tour-of-lac-megantic",
      "rating": 4,
      "resolvedName": null,
      "address": null,
      "status": null,
      "linkLabel": "Map"
    },
    {
      "id": "bike-grandes-fourches-loop-sherbrooke-north-hatley-map",
      "title": "Grandes‑Fourches Loop (Sherbrooke → North Hatley)",
      "baseTitle": "Grandes‑Fourches Loop (Sherbrooke → North Hatley)",
      "category": "bike",
      "section": "Bike Loops (50–80 km)",
      "subsection": "",
      "description": "≈ 52 km loop on the Véloroute des Grandes‑Fourches; follows the Magog, Massawippi and St. François rivers through woodlands and villages. Stop at the Golden Lion Pub, microbrewery Le Siboire or Cie Vilandré; visit the Uplands Cultural Centre, Bishop’s University and North Hatley’s shops.",
      "lat": 45.3869,
      "lng": -71.9302,
      "mapsUrl": "https://www.google.com/maps/search/?api=1&query=Parc+Lucien-Blanchard+Sherbrooke+Quebec",
      "routeUrl": "https://www.easterntownships.org/cycling/circuit/12/grandes-fourches-cycling-network-grandes-fourches-circuit",
      "rating": 4,
      "resolvedName": null,
      "address": null,
      "status": null,
      "linkLabel": "Map"
    },
    {
      "id": "bike-cleveland-loop-richmond-danville-map",
      "title": "Cleveland Loop (Richmond/Danville)",
      "baseTitle": "Cleveland Loop (Richmond/Danville)",
      "category": "bike",
      "section": "Bike Loops (50–80 km)",
      "subsection": "",
      "description": "≈ 44 km circuit with a mix of gravel (29 km) and paved roads. Highlights include Denison Lake, Grandmont Road’s maple groves and the heritage village of Danville. Enjoy lunch at Café du Couvent or beer at L’Ardoise cooperative; explore Denison Mills and the historic covered bridge.",
      "lat": 45.6675,
      "lng": -72.146,
      "mapsUrl": "https://www.google.com/maps/search/?api=1&query=La+Vieille+Gare+de+Richmond+739+rue+Principale+Nord",
      "routeUrl": "https://www.easterntownships.org/cycling/circuit/29/cleveland-loop",
      "rating": 3,
      "resolvedName": null,
      "address": null,
      "status": null,
      "linkLabel": "Map"
    },
    {
      "id": "bike-la-traverse-des-townships-sutton-lac-brome-map",
      "title": "La Traverse des Townships (Sutton → Lac Brome)",
      "baseTitle": "La Traverse des Townships (Sutton → Lac Brome)",
      "category": "bike",
      "section": "Bike Loops (50–80 km)",
      "subsection": "",
      "description": "≈ 47 km gravel loop starting in Sutton; climbs Stagecoach Road for panoramic views of the Sutton massif before descending to Brome Lake. Taste craft beers at Auberge Sutton Brouërie or À l’Abordage microbrewery; swim at Douglass Beach in Knowlton; visit Domaine Bresee vineyard.",
      "lat": 45.105,
      "lng": -72.616,
      "mapsUrl": "https://www.google.com/maps/search/?api=1&query=Club+de+Curling+Sutton+26+rue+Pleasant",
      "routeUrl": "https://www.easterntownships.org/cycling/circuit/6/la-traverse-des-townships",
      "rating": 4,
      "resolvedName": null,
      "address": null,
      "status": null,
      "linkLabel": "Map"
    },
    {
      "id": "bike-chameleon-mystic-coaticook-circuit-coaticook-map",
      "title": "Chameleon Mystic / Coaticook Circuit (Coaticook)",
      "baseTitle": "Chameleon Mystic / Coaticook Circuit (Coaticook)",
      "category": "bike",
      "section": "Bike Loops (50–80 km)",
      "subsection": "",
      "description": "≈ 59 km gravel circuit through quiet country roads and maple‑tree tunnels; part of the Pioneer Trail. After the ride, refuel at Microbrasserie Coaticook or Hop Station; browse the Coaticook dairy for ice cream.",
      "lat": 45.1358,
      "lng": -71.7996,
      "mapsUrl": "https://www.google.com/maps/search/?api=1&query=137+Rue+Michaud+Coaticook+Quebec",
      "routeUrl": "https://www.easterntownships.org/cycling/circuit/16/mystic-chameleon",
      "rating": 4,
      "resolvedName": null,
      "address": null,
      "status": null,
      "linkLabel": "Map"
    },
    {
      "id": "bike-la-grande-boucle-de-la-vallee-coaticook-valley-map",
      "title": "La Grande Boucle de la Vallée (Coaticook Valley)",
      "baseTitle": "La Grande Boucle de la Vallée (Coaticook Valley)",
      "category": "bike",
      "section": "Bike Loops (50–80 km)",
      "subsection": "",
      "description": "≈ 116 km gravel circuit with ~1 400 m of elevation across remote dirt roads; loops through Coaticook, East Hereford and Dixville. End your epic ride with a beer at Coaticook microbrewery or Hop Station; sample cheese at Fromagerie La Station.",
      "lat": 45.131,
      "lng": -71.8091,
      "mapsUrl": "https://www.google.com/maps/search/?api=1&query=Parking+of+Jean-D%27Avignon+Park+Jean-D%27Avignon+Street+Coaticook+Quebec",
      "routeUrl": "https://www.easterntownships.org/cycling/circuit/22/la-grande-boucle-de-la-vallee",
      "rating": 2,
      "resolvedName": null,
      "address": null,
      "status": null,
      "linkLabel": "Map"
    },
    {
      "id": "bike-hot-garnotte-bromont-map",
      "title": "Hot Garnotte (Bromont)",
      "baseTitle": "Hot Garnotte (Bromont)",
      "category": "bike",
      "section": "Bike Loops (50–80 km)",
      "subsection": "",
      "description": "≈ 59 km gravel route replacing the former Circuit 100 à B7 link. The old notes described steep climbs near Lac Gale, a route designed by champion cyclist Lyne Bessette, and sweeping views of the Sutton mountains. Post‑ride, enjoy coffee at Pittstop Vélo‑Café or a pint at microbrasserie Le Brouemont; explore Bromont’s boutiques.",
      "lat": 45.3202,
      "lng": -72.648,
      "mapsUrl": "https://www.google.com/maps/search/?api=1&query=Centre+national+de+cyclisme+400+rue+Shefford+Bromont+Quebec",
      "routeUrl": "https://www.easterntownships.org/cycling/circuit/4/hot-garnotte",
      "rating": 3,
      "resolvedName": null,
      "address": null,
      "status": null,
      "linkLabel": "Map"
    },
    {
      "id": "bike-boucle-des-erables-lawrenceville-map",
      "title": "Boucle des Érables (Lawrenceville)",
      "baseTitle": "Boucle des Érables (Lawrenceville)",
      "category": "bike",
      "section": "Bike Loops (50–80 km)",
      "subsection": "",
      "description": "≈ 45 km loop featuring farmland and maple groves. Agritourism stops include Marchand chez Duff general store, Jardins Zone Orange (sea‑buckthorn plantation), Cinézoo animal park and a donkey farm; a highlight is the view of Mount Orford from Rang 9 Ouest. Sample sea‑buckthorn products or visit nearby Cinezoo; stop at Jardins Zone Orange for juice and jam.",
      "lat": 45.4158,
      "lng": -72.3469,
      "mapsUrl": "https://www.google.com/maps/search/?api=1&query=2150+rue+Dandenault+Lawrenceville+Quebec",
      "routeUrl": "https://www.easterntownships.org/cycling/circuit/32/boucle-des-erables",
      "rating": 4,
      "resolvedName": null,
      "address": null,
      "status": null,
      "linkLabel": "Map"
    },
    {
      "id": "bike-sir-lyster-coaticook-region-map",
      "title": "Sir Lyster (Coaticook region)",
      "baseTitle": "Sir Lyster (Coaticook region)",
      "category": "bike",
      "section": "Bike Loops (50–80 km)",
      "subsection": "",
      "description": "≈ 34 km primarily paved loop around Lake Lyster. The itinerary passes Camping du Lac Lyster, Beaulne Museum and Parc découverte Nature; opportunities for swimming at Lake Lyster and craft beer at Hop Station. Pack a picnic for Lake Lyster beach, tour the Beaulne Museum and finish at Hop Station or Microbrasserie Coaticook.",
      "lat": 45.131,
      "lng": -71.8091,
      "mapsUrl": "https://www.google.com/maps/search/?api=1&query=Stationnement+du+Parc+Jean+Davignon+Rue+Jean-Davignon+Coaticook+Quebec",
      "routeUrl": "https://www.easterntownships.org/cycling/circuit/34/sir-lyster",
      "rating": 4,
      "resolvedName": null,
      "address": null,
      "status": null,
      "linkLabel": "Map"
    },
    {
      "id": "bike-riviere-du-nord-loop-bury-map",
      "title": "Rivière du Nord Loop (Bury)",
      "baseTitle": "Rivière du Nord Loop (Bury)",
      "category": "bike",
      "section": "Bike Loops (50–80 km)",
      "subsection": "",
      "description": "≈ 42.5 km round‑trip on unpaved roads. Scenic gravel roads wind through forests with gentle climbs; highlights include the McDermott Covered Bridge and an outdoor exhibition on Bury’s military history. Pause at the covered bridge for photos and explore the Bora Boréal floating chalets; finish with lunch at a local diner.",
      "lat": 45.4664,
      "lng": -71.5058,
      "mapsUrl": "https://www.google.com/maps/search/?api=1&query=Parc+Memorial+Bury+Quebec",
      "routeUrl": "https://www.easterntownships.org/cycling/circuit/36/riviere-du-nord",
      "rating": 3,
      "resolvedName": null,
      "address": null,
      "status": null,
      "linkLabel": "Map"
    },
    {
      "id": "bike-mont-ham-loops-saint-camille-map",
      "title": "Mont‑Ham Loops (Saint‑Camille)",
      "baseTitle": "Mont‑Ham Loops (Saint‑Camille)",
      "category": "bike",
      "section": "Bike Loops (50–80 km)",
      "subsection": "",
      "description": "≈ 49 km loop with 28.5 km unpaved and 20.5 km paved. Scenic gravel roads lead to Mont‑Ham Regional Park, where a steep hike rewards you with 360° views. Stop for coffee at Le P’tit Bonheur de Saint‑Camille; hike Mont‑Ham for panoramic vistas; camp at Camping de la Rivière Nicolet.",
      "lat": 45.6837,
      "lng": -71.7041,
      "mapsUrl": "https://www.google.com/maps/search/?api=1&query=Centre+Le+Camillois+157+rue+Miquelon+Saint-Camille",
      "routeUrl": "https://www.easterntownships.org/cycling/circuit/28/mont-ham-loops",
      "rating": 3,
      "resolvedName": null,
      "address": null,
      "status": null,
      "linkLabel": "Map"
    },
    {
      "id": "bike-le-bassin-des-deux-rivieres-cookshire-eaton-map",
      "title": "Le bassin des deux rivières (Cookshire‑Eaton)",
      "baseTitle": "Le bassin des deux rivières (Cookshire‑Eaton)",
      "category": "bike",
      "section": "Bike Loops (50–80 km)",
      "subsection": "",
      "description": "≈ 38.5 km loop with 29 km unpaved road and 9.5 km paved road. Travels along two rivers; suggested stops include the Cœur villageois of Cookshire‑Eaton, Marché du Voisinage, Les Mal‑Aimés restaurant, the Circuit des sheds panoramiques and the village of Sawyerville. Enjoy local gastronomy at Les Mal‑Aimés; climb the observation towers of the sheds panoramiques; sample produce at the Marché du Voisinage.",
      "lat": 45.4146,
      "lng": -71.626,
      "mapsUrl": "https://www.google.com/maps/search/?api=1&query=Parc+des+Braves+Cookshire-Eaton+Quebec",
      "routeUrl": "https://www.easterntownships.org/cycling/circuit/31/le-bassin-des-deux-rivieres",
      "rating": 4,
      "resolvedName": null,
      "address": null,
      "status": null,
      "linkLabel": "Map"
    },
    {
      "id": "bike-from-dock-to-dock-georgeville-fitch-bay-map",
      "title": "From Dock to Dock (Georgeville → Fitch Bay)",
      "baseTitle": "From Dock to Dock (Georgeville → Fitch Bay)",
      "category": "bike",
      "section": "Bike Loops (50–80 km)",
      "subsection": "",
      "description": "≈ 55 km figure‑8 loop, 85 % gravel. Combines lakefront roads, farmland and panoramic ridges; highlights include the Narrows Covered Bridge, Harvey Bay’s boathouses, Weir Memorial Park for a swim, Chemin Laflamme with 360° views and Auberge McGowan’s farm‑to‑table cuisine. Swim at Weir Memorial Park; lunch at Auberge McGowan or pick up provisions at Harvey Bay; cross the Narrows Covered Bridge and watch for birds.",
      "lat": 45.2055,
      "lng": -72.2466,
      "mapsUrl": "https://www.google.com/maps/search/?api=1&query=Georgeville+Wharf+Georgeville+Quebec",
      "routeUrl": "https://www.easterntownships.org/cycling/circuit/26/from-dock-to-dock",
      "rating": 4,
      "resolvedName": null,
      "address": null,
      "status": null,
      "linkLabel": "Map"
    },
    {
      "id": "bike-marecage-loop-scotstown-val-racine-map",
      "title": "Marécage Loop (Scotstown / Val‑Racine)",
      "baseTitle": "Marécage Loop (Scotstown / Val‑Racine)",
      "category": "bike",
      "section": "Bike Loops (50–80 km)",
      "subsection": "",
      "description": "≈ 54.5 km loop through forest farms and maple groves near Mont‑Mégantic National Park. Surfaces include 39 km unpaved road and 8.5 km unpaved bike path. Passes villages of Val‑Racine and Milan and features Walter‑Mackenzie Park and the Marécage‑des‑Scots regional park. Hike the interpretive trails at Parc régional du Marécage‑des‑Scots; picnic at Walter‑Mackenzie Park; stop in Val‑Racine for local produce.",
      "lat": 45.4596,
      "lng": -71.1532,
      "mapsUrl": "https://www.google.com/maps/search/?api=1&query=Parc+national+du+Mont-M%C3%A9gantic+secteur+Franceville+Quebec",
      "routeUrl": "https://www.easterntownships.org/cycling/circuit/30/marecage-loop",
      "rating": 3,
      "resolvedName": null,
      "address": null,
      "status": null,
      "linkLabel": "Map"
    },
    {
      "id": "bike-la-lanterne-rouge-brome-lake-flavours-tour-bromont-knowlton-map",
      "title": "La Lanterne Rouge / Brome Lake Flavours Tour (Bromont → Knowlton)",
      "baseTitle": "La Lanterne Rouge / Brome Lake Flavours Tour (Bromont → Knowlton)",
      "category": "bike",
      "section": "Bike Loops (50–80 km)",
      "subsection": "",
      "description": "≈ 51 km loop (intermediate difficulty) around Brome Lake, featuring panoramic lake views and gourmet stops at two vineyards and various local producers. Cycle through the Cœur villageois of Knowlton to sample pastries and antiques; swim at Douglass Beach; visit Vignoble de la Bauge and Léon Courville vineyards.",
      "lat": 45.3163,
      "lng": -72.6462,
      "mapsUrl": "https://www.google.com/maps/search/?api=1&query=Bureau+d%27information+touristique+de+Bromont+15+Bd+de+Bromont+Bromont+Quebec",
      "routeUrl": "https://www.laroutedesvins.ca/en/itinerary/la-lanterne-rouge/",
      "rating": 4,
      "resolvedName": null,
      "address": null,
      "status": null,
      "linkLabel": "Map"
    },
    {
      "id": "bike-la-doyenne-des-vignes-frelighsburg-dunham-map",
      "title": "La Doyenne des vignes (Frelighsburg ↔ Dunham)",
      "baseTitle": "La Doyenne des vignes (Frelighsburg ↔ Dunham)",
      "category": "bike",
      "section": "Bike Loops (50–80 km)",
      "subsection": "",
      "description": "≈ 76.5 km mostly paved tour through Quebec’s oldest wine region; visits up to five vineyards (Val Caudalies, Vignoble du Ruisseau, Vignoble de la Bauge, l’Ardennais and others) and microbrewery Brasserie Dunham. Sample wines at every stop, enjoy lunch at Vignoble de la Bauge’s bistro and end your day at Brasserie Dunham.",
      "lat": 45.0545,
      "lng": -72.8376,
      "mapsUrl": "https://www.google.com/maps/search/?api=1&query=Bureau+d%27information+touristique+de+Frelighsburg+1+Place+de+l%27H%C3%B4tel-de-Ville+Frelighsburg+Quebec",
      "routeUrl": "https://www.laroutedesvins.ca/circuit/la-doyenne-des-vignes/",
      "rating": 2,
      "resolvedName": null,
      "address": null,
      "status": null,
      "linkLabel": "Map"
    },
    {
      "id": "villages-sutton-maps",
      "title": "Sutton",
      "baseTitle": "Sutton",
      "category": "villages",
      "section": "Charming Villages (Cœurs Villageois)",
      "subsection": "",
      "description": "Mountain village known for outdoor adventures and a Vélosympathique cycling culture. Nearby highlights include Domaine Bresee vineyard, Le Cafetier micro‑roastery, and microbreweries À l’Abordage and Auberge Sutton Brouërie.",
      "lat": 45.1081,
      "lng": -72.6155,
      "mapsUrl": "https://www.google.com/maps/search/?api=1&query=Sutton+Quebec",
      "routeUrl": null,
      "rating": null,
      "resolvedName": null,
      "address": null,
      "status": null,
      "linkLabel": "Maps"
    },
    {
      "id": "villages-frelighsburg-maps",
      "title": "Frelighsburg",
      "baseTitle": "Frelighsburg",
      "category": "villages",
      "section": "Charming Villages (Cœurs Villageois)",
      "subsection": "",
      "description": "One of Canada’s most beautiful villages, retaining 18th‑century brick and wooden buildings such as the Freligh Mill (1839). Visit Beat & Betterave microbrewery and La Rumeur Affamée delicatessen.",
      "lat": 45.0538,
      "lng": -72.8379,
      "mapsUrl": "https://www.google.com/maps/search/?api=1&query=Frelighsburg+Quebec",
      "routeUrl": null,
      "rating": null,
      "resolvedName": null,
      "address": null,
      "status": null,
      "linkLabel": "Maps"
    },
    {
      "id": "villages-north-hatley-maps",
      "title": "North Hatley",
      "baseTitle": "North Hatley",
      "category": "villages",
      "section": "Charming Villages (Cœurs Villageois)",
      "subsection": "",
      "description": "Lakeside “dollhouse” village on Lake Massawippi. Loyalist‑era homes house art galleries, antique shops, cafés and B&Bs; a 34‑mile bike path along the Massawippi River starts here.",
      "lat": 45.2762,
      "lng": -71.9732,
      "mapsUrl": "https://www.google.com/maps/search/?api=1&query=North+Hatley+Quebec",
      "routeUrl": null,
      "rating": null,
      "resolvedName": null,
      "address": null,
      "status": null,
      "linkLabel": "Maps"
    },
    {
      "id": "villages-knowlton-lac-brome-maps",
      "title": "Knowlton (Lac‑Brome)",
      "baseTitle": "Knowlton (Lac‑Brome)",
      "category": "villages",
      "section": "Charming Villages (Cœurs Villageois)",
      "subsection": "",
      "description": "Resort town with Loyalist‑era architecture, antique shops and pastry shops. Brome Lake duck appears on many menus; check out microbrewery La Knowlton Co.",
      "lat": 45.2161,
      "lng": -72.5134,
      "mapsUrl": "https://www.google.com/maps/search/?api=1&query=Knowlton+Quebec",
      "routeUrl": null,
      "rating": null,
      "resolvedName": null,
      "address": null,
      "status": null,
      "linkLabel": "Maps"
    },
    {
      "id": "villages-eastman-maps",
      "title": "Eastman",
      "baseTitle": "Eastman",
      "category": "villages",
      "section": "Charming Villages (Cœurs Villageois)",
      "subsection": "",
      "description": "Literary village with a community library and the *Correspondances d’Eastman* festival. Walk the Parc du Temps qui Passe sundial park, follow the literary and heritage trail around Lake d’Argent, or explore Parc Missisquoi‑Nord’s trails.",
      "lat": 45.3002,
      "lng": -72.3147,
      "mapsUrl": "https://www.google.com/maps/search/?api=1&query=Eastman+Quebec",
      "routeUrl": null,
      "rating": null,
      "resolvedName": null,
      "address": null,
      "status": null,
      "linkLabel": "Maps"
    },
    {
      "id": "villages-stanbridge-east-maps",
      "title": "Stanbridge East",
      "baseTitle": "Stanbridge East",
      "category": "villages",
      "section": "Charming Villages (Cœurs Villageois)",
      "subsection": "",
      "description": "Loyalist village preserving the Anglican Church (1860), United Church (1844) and Hodge’s General Store. The Missisquoi Museum and Walbridge Barn tell local history; try L’Oeuf artisanal chocolate shop and the apple‑pie festival.",
      "lat": 45.1143,
      "lng": -72.9164,
      "mapsUrl": "https://www.google.com/maps/search/?api=1&query=Stanbridge+East+Quebec",
      "routeUrl": null,
      "rating": null,
      "resolvedName": null,
      "address": null,
      "status": null,
      "linkLabel": "Maps"
    },
    {
      "id": "villages-piopolis-maps",
      "title": "Piopolis",
      "baseTitle": "Piopolis",
      "category": "villages",
      "section": "Charming Villages (Cœurs Villageois)",
      "subsection": "",
      "description": "Waterfront village on Lake Mégantic with mountain views. Walk the heritage trail and learn local history at the Halte des Zouaves; enjoy sugar pie at the general store or dine at Auberge Au Soleil Levant.",
      "lat": 45.4875,
      "lng": -70.9032,
      "mapsUrl": "https://www.google.com/maps/search/?api=1&query=Piopolis+Quebec",
      "routeUrl": null,
      "rating": null,
      "resolvedName": null,
      "address": null,
      "status": null,
      "linkLabel": "Maps"
    },
    {
      "id": "villages-lambton-maps",
      "title": "Lambton",
      "baseTitle": "Lambton",
      "category": "villages",
      "section": "Charming Villages (Cœurs Villageois)",
      "subsection": "",
      "description": "Overlooks Lake Saint‑François with the majestic St‑Vital church and a walking circuit featuring an art gallery. Stay at B&Bs or campgrounds and explore nearby Frontenac National Park.",
      "lat": 45.8398,
      "lng": -71.0892,
      "mapsUrl": "https://www.google.com/maps/search/?api=1&query=Lambton+Quebec",
      "routeUrl": null,
      "rating": null,
      "resolvedName": null,
      "address": null,
      "status": null,
      "linkLabel": "Maps"
    },
    {
      "id": "scenic-brome-missisquoi-wine-route-maps",
      "title": "Brome‑Missisquoi Wine Route",
      "baseTitle": "Brome‑Missisquoi Wine Route",
      "category": "scenic",
      "section": "Scenic Drives & Routes",
      "subsection": "",
      "description": "160 km marked route crossing hills and villages; links 24–25 vineyards and accounts for 60 % of Quebec’s wine production. “Amis de la Route des vins” stops include restaurants, B&Bs and attractions.",
      "lat": 45.1262,
      "lng": -72.801,
      "mapsUrl": "https://www.google.com/maps/search/?api=1&query=Brome-Missisquoi+Wine+Route+Quebec",
      "routeUrl": null,
      "rating": null,
      "resolvedName": null,
      "address": null,
      "status": null,
      "linkLabel": "Maps",
      "line": [
        [
          45.3157,
          -72.6424
        ],
        [
          45.2849,
          -72.9889
        ],
        [
          45.1192,
          -72.9798
        ],
        [
          45.1143,
          -72.9164
        ],
        [
          45.027,
          -73.065
        ],
        [
          45.0538,
          -72.8379
        ],
        [
          45.1081,
          -72.6155
        ],
        [
          45.2161,
          -72.5134
        ],
        [
          45.1991,
          -72.7492
        ],
        [
          45.1304,
          -72.8002
        ]
      ]
    },
    {
      "id": "scenic-townships-trail-chemin-des-cantons-maps",
      "title": "Townships Trail (Chemin des Cantons)",
      "baseTitle": "Townships Trail (Chemin des Cantons)",
      "category": "scenic",
      "section": "Scenic Drives & Routes",
      "subsection": "",
      "description": "430 km heritage route with 38 stops across 31 towns. Features Victorian homes, round barns, covered bridges, museums and churches.",
      "lat": 45.3955,
      "lng": -71.921,
      "mapsUrl": "https://www.google.com/maps/search/?api=1&query=Chemin+des+Cantons+Eastern+Townships",
      "routeUrl": null,
      "rating": null,
      "resolvedName": null,
      "address": null,
      "status": null,
      "linkLabel": "Maps",
      "line": [
        [
          45.316,
          -72.6462
        ],
        [
          45.3002,
          -72.3147
        ],
        [
          45.2674,
          -72.1461
        ],
        [
          45.2762,
          -71.9732
        ],
        [
          45.4009,
          -71.8917
        ],
        [
          45.4146,
          -71.626
        ],
        [
          45.4664,
          -71.5058
        ],
        [
          45.1569,
          -71.8004
        ],
        [
          45.2055,
          -72.2466
        ],
        [
          45.582,
          -70.8886
        ]
      ]
    },
    {
      "id": "scenic-summit-drive-route-des-sommets-maps",
      "title": "Summit Drive (Route des Sommets)",
      "baseTitle": "Summit Drive (Route des Sommets)",
      "category": "scenic",
      "section": "Scenic Drives & Routes",
      "subsection": "",
      "description": "193 km circuit linking the highest peaks between La Patrie and Saint‑Adrien. Offers panoramic views of mountains and lakes, plus stargazing opportunities in the Dark‑Sky Reserve.",
      "lat": 45.4821,
      "lng": -71.012,
      "mapsUrl": "https://www.google.com/maps/search/?api=1&query=Route+des+Sommets+Eastern+Townships",
      "routeUrl": null,
      "rating": null,
      "resolvedName": null,
      "address": null,
      "status": null,
      "linkLabel": "Maps",
      "line": [
        [
          45.399,
          -71.258
        ],
        [
          45.367,
          -71.086
        ],
        [
          45.456,
          -71.179
        ],
        [
          45.582,
          -70.8886
        ],
        [
          45.4875,
          -70.9032
        ],
        [
          45.671,
          -70.868
        ],
        [
          45.8398,
          -71.0892
        ],
        [
          45.787,
          -71.35
        ],
        [
          45.733,
          -71.65
        ],
        [
          45.673,
          -71.659
        ]
      ]
    },
    {
      "id": "beaches-douglass-beach-lac-brome-maps",
      "title": "Douglass Beach (Lac Brome)",
      "baseTitle": "Douglass Beach (Lac Brome)",
      "category": "beaches",
      "section": "Lakes & Beaches for a Refreshing Dip",
      "subsection": "",
      "description": "Public beach with soft sand, volleyball court, picnic tables and views of Brome Lake. Perfect for a quick swim after visiting Knowlton.",
      "lat": 45.2243,
      "lng": -72.5164,
      "mapsUrl": "https://www.google.com/maps/search/?api=1&query=Douglass+Beach+Lac+Brome",
      "routeUrl": null,
      "rating": null,
      "resolvedName": null,
      "address": null,
      "status": null,
      "linkLabel": "Maps"
    },
    {
      "id": "beaches-lake-lyster-municipal-beach-maps",
      "title": "Lake Lyster Municipal Beach",
      "baseTitle": "Lake Lyster Municipal Beach",
      "category": "beaches",
      "section": "Lakes & Beaches for a Refreshing Dip",
      "subsection": "",
      "description": "200‑m sandy beach in Coaticook with lifeguards, picnic tables and boat rentals; offers a stunning view of Mont Pinacle.",
      "lat": 45.0107,
      "lng": -71.9101,
      "mapsUrl": "https://www.google.com/maps/search/?api=1&query=Plage+Lac+Lyster+Coaticook",
      "routeUrl": null,
      "rating": null,
      "resolvedName": null,
      "address": null,
      "status": null,
      "linkLabel": "Maps"
    },
    {
      "id": "beaches-baie-des-sables-beach-lac-megantic-maps",
      "title": "Baie‑des‑Sables Beach (Lac Mégantic)",
      "baseTitle": "Baie‑des‑Sables Beach (Lac Mégantic)",
      "category": "beaches",
      "section": "Lakes & Beaches for a Refreshing Dip",
      "subsection": "",
      "description": "Family‑friendly beach at Station touristique Baie‑des‑Sables with restaurants, rental shops and watersports.",
      "lat": 45.5946,
      "lng": -70.9108,
      "mapsUrl": "https://www.google.com/maps/search/?api=1&query=Station+touristique+Baie-des-Sables+plage+Lac-M%C3%A9gantic+Quebec",
      "routeUrl": null,
      "rating": null,
      "resolvedName": null,
      "address": null,
      "status": null,
      "linkLabel": "Maps"
    },
    {
      "id": "beaches-camping-du-lac-mckenzie-lac-brompton-maps",
      "title": "Camping du lac McKenzie (Lac Brompton)",
      "baseTitle": "Camping du lac McKenzie (Lac Brompton)",
      "category": "beaches",
      "section": "Lakes & Beaches for a Refreshing Dip",
      "subsection": "",
      "description": "Public beach with pristine water quality and activities like volleyball and kayaking; day passes available.",
      "lat": 45.4648,
      "lng": -72.1932,
      "mapsUrl": "https://www.google.com/maps/search/?api=1&query=Camping+du+lac+McKenzie+Brompton",
      "routeUrl": null,
      "rating": null,
      "resolvedName": null,
      "address": null,
      "status": null,
      "linkLabel": "Maps"
    },
    {
      "id": "beaches-national-park-beaches-lacs-stukely-fraser-choiniere-baie-aux-rats-musque",
      "title": "National‑Park Beaches (Lacs Stukely, Fraser, Choinière & Baie aux Rats‑Musqués) - Stukely",
      "baseTitle": "National‑Park Beaches (Lacs Stukely, Fraser, Choinière & Baie aux Rats‑Musqués)",
      "category": "beaches",
      "section": "Lakes & Beaches for a Refreshing Dip",
      "subsection": "",
      "description": "Mont‑Orford National Park offers beaches on Lakes Stukely and Fraser, Yamaska’s park has a beach at Choinière reservoir, and Frontenac’s park has a beach at Baie aux Rats‑Musqués on Grand Lac Saint‑François.",
      "lat": 45.3703,
      "lng": -72.2313,
      "mapsUrl": "https://www.google.com/maps/search/?api=1&query=Plage+du+Lac+Stukely+Parc+national+du+Mont-Orford",
      "routeUrl": null,
      "rating": null,
      "resolvedName": null,
      "address": null,
      "status": null,
      "linkLabel": "Stukely"
    },
    {
      "id": "beaches-national-park-beaches-lacs-stukely-fraser-choiniere-baie-aux-rats-musque",
      "title": "National‑Park Beaches (Lacs Stukely, Fraser, Choinière & Baie aux Rats‑Musqués) - Fraser",
      "baseTitle": "National‑Park Beaches (Lacs Stukely, Fraser, Choinière & Baie aux Rats‑Musqués)",
      "category": "beaches",
      "section": "Lakes & Beaches for a Refreshing Dip",
      "subsection": "",
      "description": "Mont‑Orford National Park offers beaches on Lakes Stukely and Fraser, Yamaska’s park has a beach at Choinière reservoir, and Frontenac’s park has a beach at Baie aux Rats‑Musqués on Grand Lac Saint‑François.",
      "lat": 45.3191,
      "lng": -72.2078,
      "mapsUrl": "https://www.google.com/maps/search/?api=1&query=Plage+du+Lac+Fraser+Parc+national+du+Mont-Orford",
      "routeUrl": null,
      "rating": null,
      "resolvedName": null,
      "address": null,
      "status": null,
      "linkLabel": "Fraser"
    },
    {
      "id": "beaches-national-park-beaches-lacs-stukely-fraser-choiniere-baie-aux-rats-musque",
      "title": "National‑Park Beaches (Lacs Stukely, Fraser, Choinière & Baie aux Rats‑Musqués) - Choinière",
      "baseTitle": "National‑Park Beaches (Lacs Stukely, Fraser, Choinière & Baie aux Rats‑Musqués)",
      "category": "beaches",
      "section": "Lakes & Beaches for a Refreshing Dip",
      "subsection": "",
      "description": "Mont‑Orford National Park offers beaches on Lakes Stukely and Fraser, Yamaska’s park has a beach at Choinière reservoir, and Frontenac’s park has a beach at Baie aux Rats‑Musqués on Grand Lac Saint‑François.",
      "lat": 45.4682,
      "lng": -72.6535,
      "mapsUrl": "https://www.google.com/maps/search/?api=1&query=Plage+du+r%C3%A9servoir+Choini%C3%A8re+Parc+national+de+la+Yamaska",
      "routeUrl": null,
      "rating": null,
      "resolvedName": null,
      "address": null,
      "status": null,
      "linkLabel": "Choinière"
    },
    {
      "id": "beaches-national-park-beaches-lacs-stukely-fraser-choiniere-baie-aux-rats-musque",
      "title": "National‑Park Beaches (Lacs Stukely, Fraser, Choinière & Baie aux Rats‑Musqués) - Frontenac",
      "baseTitle": "National‑Park Beaches (Lacs Stukely, Fraser, Choinière & Baie aux Rats‑Musqués)",
      "category": "beaches",
      "section": "Lakes & Beaches for a Refreshing Dip",
      "subsection": "",
      "description": "Mont‑Orford National Park offers beaches on Lakes Stukely and Fraser, Yamaska’s park has a beach at Choinière reservoir, and Frontenac’s park has a beach at Baie aux Rats‑Musqués on Grand Lac Saint‑François.",
      "lat": 45.8526,
      "lng": -71.1965,
      "mapsUrl": "https://www.google.com/maps/search/?api=1&query=Baie+aux+Rats-Musqu%C3%A9s+Parc+national+de+Frontenac",
      "routeUrl": null,
      "rating": null,
      "resolvedName": null,
      "address": null,
      "status": null,
      "linkLabel": "Frontenac"
    },
    {
      "id": "beaches-lake-memphremagog-public-beaches-plage-des-cantons-plage-des-cantons",
      "title": "Lake Memphrémagog public beaches - Plage des Cantons",
      "baseTitle": "Lake Memphrémagog public beaches",
      "category": "beaches",
      "section": "Lakes & Beaches for a Refreshing Dip",
      "subsection": "",
      "description": "42 km glacial lake with three public beaches in Magog; offers boat rentals, cruises and watersports.",
      "lat": 45.2618,
      "lng": -72.1306,
      "mapsUrl": "https://www.google.com/maps/search/?api=1&query=Plage+des+Cantons+Magog+Quebec",
      "routeUrl": null,
      "rating": null,
      "resolvedName": null,
      "address": null,
      "status": null,
      "linkLabel": "Plage des Cantons"
    },
    {
      "id": "beaches-lake-memphremagog-public-beaches-pointe-merry-pointe-merry",
      "title": "Lake Memphrémagog public beaches - Pointe-Merry",
      "baseTitle": "Lake Memphrémagog public beaches",
      "category": "beaches",
      "section": "Lakes & Beaches for a Refreshing Dip",
      "subsection": "",
      "description": "42 km glacial lake with three public beaches in Magog; offers boat rentals, cruises and watersports.",
      "lat": 45.2674,
      "lng": -72.1461,
      "mapsUrl": "https://www.google.com/maps/search/?api=1&query=Plage+Pointe-Merry+Magog+Quebec",
      "routeUrl": null,
      "rating": null,
      "resolvedName": null,
      "address": null,
      "status": null,
      "linkLabel": "Pointe-Merry"
    },
    {
      "id": "beaches-lake-memphremagog-public-beaches-plage-de-louest-plage-de-louest",
      "title": "Lake Memphrémagog public beaches - Plage de l’Ouest",
      "baseTitle": "Lake Memphrémagog public beaches",
      "category": "beaches",
      "section": "Lakes & Beaches for a Refreshing Dip",
      "subsection": "",
      "description": "42 km glacial lake with three public beaches in Magog; offers boat rentals, cruises and watersports.",
      "lat": 45.2515,
      "lng": -72.1661,
      "mapsUrl": "https://www.google.com/maps/search/?api=1&query=Plage+de+l%27Ouest+Magog+Quebec",
      "routeUrl": null,
      "rating": null,
      "resolvedName": null,
      "address": null,
      "status": null,
      "linkLabel": "Plage de l’Ouest"
    },
    {
      "id": "beaches-lake-massawippi-north-hatley-pleasant-view-beach-pleasant-view-beach",
      "title": "Lake Massawippi (North Hatley) - Pleasant View Beach",
      "baseTitle": "Lake Massawippi (North Hatley)",
      "category": "beaches",
      "section": "Lakes & Beaches for a Refreshing Dip",
      "subsection": "",
      "description": "Deep, clear lake with swimming at North Hatley’s wharf; boat rentals available and the village is charming.",
      "lat": 45.2781,
      "lng": -71.9778,
      "mapsUrl": "https://www.google.com/maps/search/?api=1&query=Pleasant+View+Beach+North+Hatley+Quebec",
      "routeUrl": null,
      "rating": null,
      "resolvedName": null,
      "address": null,
      "status": null,
      "linkLabel": "Pleasant View Beach"
    },
    {
      "id": "beaches-lake-massawippi-north-hatley-north-hatley-pier-north-hatley-pier",
      "title": "Lake Massawippi (North Hatley) - North Hatley Pier",
      "baseTitle": "Lake Massawippi (North Hatley)",
      "category": "beaches",
      "section": "Lakes & Beaches for a Refreshing Dip",
      "subsection": "",
      "description": "Deep, clear lake with swimming at North Hatley’s wharf; boat rentals available and the village is charming.",
      "lat": 45.2765,
      "lng": -71.9727,
      "mapsUrl": "https://www.google.com/maps/search/?api=1&query=North+Hatley+Pier+Main+Street",
      "routeUrl": null,
      "rating": null,
      "resolvedName": null,
      "address": null,
      "status": null,
      "linkLabel": "North Hatley Pier"
    },
    {
      "id": "cafes-cafe-hubert-saint-jean-sherbrooke-magog-sherbrooke-king-sherbrooke-king",
      "title": "Café Hubert Saint‑Jean (Sherbrooke/Magog) - Sherbrooke King",
      "baseTitle": "Café Hubert Saint‑Jean (Sherbrooke/Magog)",
      "category": "cafes",
      "section": "Cafés, Coffee Roasteries & Lunch Spots",
      "subsection": "Coffee roasteries and village cafés",
      "description": "The region’s oldest roaster (1923), producing about 60,000 pounds of coffee annually and ensuring fair pay for Honduran growers. Google Maps currently marks the Magog location permanently closed.",
      "lat": 45.3991722,
      "lng": -71.8967883,
      "mapsUrl": "https://www.google.com/maps?cid=7561760882664496372",
      "routeUrl": null,
      "rating": 4,
      "resolvedName": "Café Hubert Saint-Jean",
      "address": "455 Rue King Ouest, Sherbrooke, QC J1H 6E9",
      "status": "Permanently closed",
      "linkLabel": "Sherbrooke King"
    },
    {
      "id": "cafes-cafe-hubert-saint-jean-sherbrooke-magog-sherbrooke-bourque-sherbrooke-bour",
      "title": "Café Hubert Saint‑Jean (Sherbrooke/Magog) - Sherbrooke Bourque",
      "baseTitle": "Café Hubert Saint‑Jean (Sherbrooke/Magog)",
      "category": "cafes",
      "section": "Cafés, Coffee Roasteries & Lunch Spots",
      "subsection": "Coffee roasteries and village cafés",
      "description": "The region’s oldest roaster (1923), producing about 60,000 pounds of coffee annually and ensuring fair pay for Honduran growers. Google Maps currently marks the Magog location permanently closed.",
      "lat": 45.3727806,
      "lng": -71.9864879,
      "mapsUrl": "https://www.google.com/maps?cid=13504275005726709084",
      "routeUrl": null,
      "rating": 4,
      "resolvedName": "Hubert St-Jean",
      "address": "4797 Boul Bourque, Sherbrooke, QC J1N 2G8",
      "status": "Permanently closed",
      "linkLabel": "Sherbrooke Bourque"
    },
    {
      "id": "cafes-cafe-hubert-saint-jean-sherbrooke-magog-magog-permanently-closed",
      "title": "Café Hubert Saint‑Jean (Sherbrooke/Magog) - Magog - permanently closed",
      "baseTitle": "Café Hubert Saint‑Jean (Sherbrooke/Magog)",
      "category": "cafes",
      "section": "Cafés, Coffee Roasteries & Lunch Spots",
      "subsection": "Coffee roasteries and village cafés",
      "description": "The region’s oldest roaster (1923), producing about 60,000 pounds of coffee annually and ensuring fair pay for Honduran growers. Google Maps currently marks the Magog location permanently closed.",
      "lat": 45.266335,
      "lng": -72.1545627,
      "mapsUrl": "https://www.google.com/maps?cid=11777388905794438171",
      "routeUrl": null,
      "rating": 4,
      "resolvedName": "Café Hubert Saint-Jean - Magog",
      "address": "464 Rue Principale O, Magog, QC J1X 2A9",
      "status": "Permanently closed",
      "linkLabel": "Magog - permanently closed"
    },
    {
      "id": "cafes-brulerie-faro-sherbrooke-downtown-downtown",
      "title": "Brûlerie Faro (Sherbrooke) - Downtown",
      "baseTitle": "Brûlerie Faro (Sherbrooke)",
      "category": "cafes",
      "section": "Cafés, Coffee Roasteries & Lunch Spots",
      "subsection": "Coffee roasteries and village cafés",
      "description": "Established in 1982 with multiple shops, this roaster offers classic, sustainable and limited‑edition blends; it recently adopted biodegradable cups and waste‑reduction measures.",
      "lat": 45.404276,
      "lng": -71.89198,
      "mapsUrl": "https://www.google.com/maps?cid=5902462176329438927",
      "routeUrl": null,
      "rating": 3,
      "resolvedName": "Brûlerie FARO",
      "address": "180 Rue Wellington N, Sherbrooke, QC J1H 5B9",
      "status": null,
      "linkLabel": "Downtown"
    },
    {
      "id": "cafes-brulerie-faro-sherbrooke-roastery-roastery",
      "title": "Brûlerie Faro (Sherbrooke) - Roastery",
      "baseTitle": "Brûlerie Faro (Sherbrooke)",
      "category": "cafes",
      "section": "Cafés, Coffee Roasteries & Lunch Spots",
      "subsection": "Coffee roasteries and village cafés",
      "description": "Established in 1982 with multiple shops, this roaster offers classic, sustainable and limited‑edition blends; it recently adopted biodegradable cups and waste‑reduction measures.",
      "lat": 45.3906875,
      "lng": -71.9380141,
      "mapsUrl": "https://www.google.com/maps?cid=16329186298395429249",
      "routeUrl": null,
      "rating": 3,
      "resolvedName": "Café Faro inc. - Centre de torréfaction",
      "address": "930 Rue Blais, Sherbrooke, QC J1K 2B7",
      "status": null,
      "linkLabel": "Roastery"
    },
    {
      "id": "cafes-brulerie-faro-sherbrooke-lennoxville-lennoxville",
      "title": "Brûlerie Faro (Sherbrooke) - Lennoxville",
      "baseTitle": "Brûlerie Faro (Sherbrooke)",
      "category": "cafes",
      "section": "Cafés, Coffee Roasteries & Lunch Spots",
      "subsection": "Coffee roasteries and village cafés",
      "description": "Established in 1982 with multiple shops, this roaster offers classic, sustainable and limited‑edition blends; it recently adopted biodegradable cups and waste‑reduction measures.",
      "lat": 45.3672532,
      "lng": -71.856421,
      "mapsUrl": "https://www.google.com/maps?cid=2242667120801273867",
      "routeUrl": null,
      "rating": 3,
      "resolvedName": "Brûlerie FARO",
      "address": "112 Queen St, Sherbrooke, Quebec J1M 1J6",
      "status": null,
      "linkLabel": "Lennoxville"
    },
    {
      "id": "cafes-brulerie-virgin-hill-brome-lake-foster-maps",
      "title": "Brûlerie Virgin Hill (Brome Lake/Foster)",
      "baseTitle": "Brûlerie Virgin Hill (Brome Lake/Foster)",
      "category": "cafes",
      "section": "Cafés, Coffee Roasteries & Lunch Spots",
      "subsection": "Coffee roasteries and village cafés",
      "description": "Family‑owned for two decades and sourcing beans from 18 countries; visitors can learn the art of roasting during workshops.",
      "lat": 45.2929001,
      "lng": -72.5009003,
      "mapsUrl": "https://www.google.com/maps?cid=11716785563854412930",
      "routeUrl": null,
      "rating": 4,
      "resolvedName": "Brûlerie Virgin Hill Coffee",
      "address": "770 Chem. Lakeside, Foster, QC J0E 1R0",
      "status": null,
      "linkLabel": "Maps"
    },
    {
      "id": "cafes-fitch-bay-cafe-magog-maps",
      "title": "Fitch Bay Café (Magog)",
      "baseTitle": "Fitch Bay Café (Magog)",
      "category": "cafes",
      "section": "Cafés, Coffee Roasteries & Lunch Spots",
      "subsection": "Coffee roasteries and village cafés",
      "description": "Micro‑roaster located in Magog’s historic Cotton Mills building; produces 7–8 tons of coffee annually across 20–25 blends.",
      "lat": 45.2626533,
      "lng": -72.1399002,
      "mapsUrl": "https://www.google.com/maps?cid=1617115378925504806",
      "routeUrl": null,
      "rating": 4,
      "resolvedName": "Fitch Bay Café",
      "address": "270 Rue Principale E local 100, Magog, QC J1X 4X5",
      "status": null,
      "linkLabel": "Maps"
    },
    {
      "id": "cafes-le-cafe-de-la-brulerie-granby-maps",
      "title": "Le Café de la Brûlerie (Granby)",
      "baseTitle": "Le Café de la Brûlerie (Granby)",
      "category": "cafes",
      "section": "Cafés, Coffee Roasteries & Lunch Spots",
      "subsection": "Coffee roasteries and village cafés",
      "description": "Café that roasts and grinds its own beans on site; offers a range of beverages and sells around 20 coffee blends; located near the Estriade and Montérégiade bike paths.",
      "lat": 45.3974781,
      "lng": -72.7161348,
      "mapsUrl": "https://www.google.com/maps?cid=16074447921130940409",
      "routeUrl": null,
      "rating": 3,
      "resolvedName": "Café De La Brûlerie (Le)",
      "address": "4 Rue de la Gare, Granby, QC J2G 4C7",
      "status": null,
      "linkLabel": "Maps"
    },
    {
      "id": "cafes-geogene-micro-torrefacteur-sherbrooke-magog-sherbrooke-sherbrooke",
      "title": "Géogène Micro‑Torréfacteur (Sherbrooke/Magog) - Sherbrooke",
      "baseTitle": "Géogène Micro‑Torréfacteur (Sherbrooke/Magog)",
      "category": "cafes",
      "section": "Cafés, Coffee Roasteries & Lunch Spots",
      "subsection": "Coffee roasteries and village cafés",
      "description": "Ethical micro‑roaster with locations in Sherbrooke and Magog, offering about ten blends and emphasising conscientious practices.",
      "lat": 45.407862,
      "lng": -71.8769014,
      "mapsUrl": "https://www.google.com/maps?cid=17099840186639355711",
      "routeUrl": null,
      "rating": 3,
      "resolvedName": "Géogène Micro-torréfacteur",
      "address": "538 Rte 112, Sherbrooke, Quebec J1G 1B5",
      "status": null,
      "linkLabel": "Sherbrooke"
    },
    {
      "id": "cafes-geogene-micro-torrefacteur-sherbrooke-magog-magog-magog",
      "title": "Géogène Micro‑Torréfacteur (Sherbrooke/Magog) - Magog",
      "baseTitle": "Géogène Micro‑Torréfacteur (Sherbrooke/Magog)",
      "category": "cafes",
      "section": "Cafés, Coffee Roasteries & Lunch Spots",
      "subsection": "Coffee roasteries and village cafés",
      "description": "Ethical micro‑roaster with locations in Sherbrooke and Magog, offering about ten blends and emphasising conscientious practices.",
      "lat": 45.2654896,
      "lng": -72.1513491,
      "mapsUrl": "https://www.google.com/maps?cid=10364914515740539007",
      "routeUrl": null,
      "rating": 3,
      "resolvedName": "Géogène Café - Magog",
      "address": "290 Rue Principale O, Magog, QC J1X 2A9",
      "status": null,
      "linkLabel": "Magog"
    },
    {
      "id": "cafes-appalaches-torrefacteur-mansonville-maps",
      "title": "Appalaches Torréfacteur (Mansonville)",
      "baseTitle": "Appalaches Torréfacteur (Mansonville)",
      "category": "cafes",
      "section": "Cafés, Coffee Roasteries & Lunch Spots",
      "subsection": "Coffee roasteries and village cafés",
      "description": "Small roastery (opened 2020) that offers a dozen grinds and partners with local producers such as La Pinte dairy.",
      "lat": 45.0501048,
      "lng": -72.3912888,
      "mapsUrl": "https://www.google.com/maps?cid=18431435550957312562",
      "routeUrl": null,
      "rating": 3,
      "resolvedName": "Appalaches | Torréfacteur - Roaster",
      "address": "4 Rue des Pins, Mansonville, QC J0E 1X0",
      "status": null,
      "linkLabel": "Maps"
    },
    {
      "id": "cafes-cafe-du-couvent-coop-richmond-maps",
      "title": "Café du Couvent Coop (Richmond)",
      "baseTitle": "Café du Couvent Coop (Richmond)",
      "category": "cafes",
      "section": "Cafés, Coffee Roasteries & Lunch Spots",
      "subsection": "Coffee roasteries and village cafés",
      "description": "Café housed in a heritage building; serves vegetarian meals, desserts and coffee from local roasters in a warm, charming atmosphere.",
      "lat": 45.6683807,
      "lng": -72.1493377,
      "mapsUrl": "https://www.google.com/maps?cid=8204218029708935250",
      "routeUrl": null,
      "rating": 4,
      "resolvedName": "Café du Couvent",
      "address": "200 Rue du Couvent #120, Richmond, QC J0B 2H0",
      "status": null,
      "linkLabel": "Maps"
    },
    {
      "id": "cafes-cafe-madame-hortense-granby-maps",
      "title": "Café Madame Hortense (Granby)",
      "baseTitle": "Café Madame Hortense (Granby)",
      "category": "cafes",
      "section": "Cafés, Coffee Roasteries & Lunch Spots",
      "subsection": "Coffee roasteries and village cafés",
      "description": "Cozy café combining a coffee shop with a gift shop and local artwork, making it a hidden treasure.",
      "lat": 45.3957236,
      "lng": -72.732648,
      "mapsUrl": "https://www.google.com/maps?cid=18216595271482531792",
      "routeUrl": null,
      "rating": 4,
      "resolvedName": "Madame Hortense",
      "address": "360 Rue Cowie #206, Granby, QC J2G 3V8",
      "status": null,
      "linkLabel": "Maps"
    },
    {
      "id": "cafes-the-pleasant-hotel-cafe-sutton-maps",
      "title": "The Pleasant Hotel & Café (Sutton)",
      "baseTitle": "The Pleasant Hotel & Café (Sutton)",
      "category": "cafes",
      "section": "Cafés, Coffee Roasteries & Lunch Spots",
      "subsection": "Coffee roasteries and village cafés",
      "description": "Contemporary café inside a boutique hotel; serves micro‑roasted coffee and a gourmet menu featuring local flavours.",
      "lat": 45.1070335,
      "lng": -72.6146832,
      "mapsUrl": "https://www.google.com/maps?cid=13859417606446664847",
      "routeUrl": null,
      "rating": 3,
      "resolvedName": "Le Pleasant Hôtel, Sutton",
      "address": "1 Rue Pleasant, Sutton, QC J0E 2K0",
      "status": null,
      "linkLabel": "Maps"
    },
    {
      "id": "cafes-espace-boho-waterloo-maps",
      "title": "Espace Boho (Waterloo)",
      "baseTitle": "Espace Boho (Waterloo)",
      "category": "cafes",
      "section": "Cafés, Coffee Roasteries & Lunch Spots",
      "subsection": "Coffee roasteries and village cafés",
      "description": "Café‑boutique offering coffee drinks and light meals with a basement thrift shop for vintage finds.",
      "lat": 45.3433219,
      "lng": -72.5158261,
      "mapsUrl": "https://www.google.com/maps?cid=4626481146186579516",
      "routeUrl": null,
      "rating": 3,
      "resolvedName": "Espace Boho",
      "address": "4796 Rue Foster, Waterloo, QC J0E 2N0",
      "status": null,
      "linkLabel": "Maps"
    },
    {
      "id": "cafes-loeuf-auberge-loeuf-mystic-maps",
      "title": "L’Oeuf / Auberge L’Oeuf (Mystic)",
      "baseTitle": "L’Oeuf / Auberge L’Oeuf (Mystic)",
      "category": "cafes",
      "section": "Cafés, Coffee Roasteries & Lunch Spots",
      "subsection": "Coffee roasteries and village cafés",
      "description": "Café‑inn that roasts coffee on site and serves it in a charming setting near heritage attractions like the 12‑sided Walbridge Barn and Missisquoi Museum.",
      "lat": 45.1540547,
      "lng": -72.986941,
      "mapsUrl": "https://www.google.com/maps?cid=5857317595333889135",
      "routeUrl": null,
      "rating": 4,
      "resolvedName": "L'Oeuf",
      "address": "229 Chem. de Mystic, Saint-Ignace-de-Stanbridge, QC J0J 1Y0",
      "status": null,
      "linkLabel": "Maps"
    },
    {
      "id": "cafes-la-shop-magog-maps",
      "title": "La Shop (Magog)",
      "baseTitle": "La Shop (Magog)",
      "category": "cafes",
      "section": "Cafés, Coffee Roasteries & Lunch Spots",
      "subsection": "Coffee roasteries and village cafés",
      "description": "Casual café‑bar popular for grilled‑cheese sandwiches and café au lait; offers a warm atmosphere ideal for post‑ride relaxation.",
      "lat": 45.2626744,
      "lng": -72.1396346,
      "mapsUrl": "https://www.google.com/maps?cid=9185500459407972777",
      "routeUrl": null,
      "rating": 3,
      "resolvedName": "La Shop",
      "address": "274 Rue Principale E, Magog, QC J1X 4X5",
      "status": null,
      "linkLabel": "Maps"
    },
    {
      "id": "dining-les-cocagnes-frelighsburg-maps",
      "title": "Les Cocagnes (Frelighsburg)",
      "baseTitle": "Les Cocagnes (Frelighsburg)",
      "category": "dining",
      "section": "Cafés, Coffee Roasteries & Lunch Spots",
      "subsection": "Farm‑to‑table & country‑style dining",
      "description": "Agro‑ecological collective farm hosting a country‑style table in summer (mid‑June to late September). Twenty‑one guest chefs prepare five‑course meals under a pergola using the farm’s organic vegetables, with wine, cider or beer pairings.",
      "lat": 45.0591051,
      "lng": -72.827313,
      "mapsUrl": "https://www.google.com/maps?cid=17900956351918357100",
      "routeUrl": null,
      "rating": 5,
      "resolvedName": "Les Cocagnes",
      "address": "33 Chem. de Dunham, Frelighsburg, QC J0J 1C0",
      "status": null,
      "linkLabel": "Maps"
    },
    {
      "id": "dining-lespace-old-mill-stanbridge-east-maps",
      "title": "L’Espace Old Mill (Stanbridge‑East)",
      "baseTitle": "L’Espace Old Mill (Stanbridge‑East)",
      "category": "dining",
      "section": "Cafés, Coffee Roasteries & Lunch Spots",
      "subsection": "Farm‑to‑table & country‑style dining",
      "description": "Farm, restaurant and inn overseen by market gardener Jean‑Martin Fortier and Chef Éric Gendron. Awarded a Michelin Green Star, it offers a five‑course tasting menu based on produce from its gardens and Brome‑Missisquoi region.",
      "lat": 45.1202462,
      "lng": -72.9153428,
      "mapsUrl": "https://www.google.com/maps?cid=17059320318080269848",
      "routeUrl": null,
      "rating": 5,
      "resolvedName": "Espace Old Mill",
      "address": "7 Chem. Caleb Tree, Stanbridge East, QC J0J 2H0",
      "status": null,
      "linkLabel": "Maps"
    },
    {
      "id": "dining-ferme-au-pied-leve-magog-maps",
      "title": "Ferme Au pied levé (Magog)",
      "baseTitle": "Ferme Au pied levé (Magog)",
      "category": "dining",
      "section": "Cafés, Coffee Roasteries & Lunch Spots",
      "subsection": "Farm‑to‑table & country‑style dining",
      "description": "Working farm raising Highland cattle, pigs, goats and geese while growing its own vegetables and herbs. Hosts a six‑course gourmet dinner and hearty breakfast (BYOB); guests can stroll the grounds and meet the animals.",
      "lat": 45.1774988,
      "lng": -72.14069,
      "mapsUrl": "https://www.google.com/maps?cid=16990125952436853202",
      "routeUrl": null,
      "rating": 4,
      "resolvedName": "Ferme Au Pied Levé",
      "address": "1107 Chem. de Fitch Bay, Magog, QC J1X 3W2",
      "status": null,
      "linkLabel": "Maps"
    },
    {
      "id": "dining-les-mal-aimes-cookshire-eaton-maps",
      "title": "Les Mal‑Aimés (Cookshire‑Eaton)",
      "baseTitle": "Les Mal‑Aimés (Cookshire‑Eaton)",
      "category": "dining",
      "section": "Cafés, Coffee Roasteries & Lunch Spots",
      "subsection": "Farm‑to‑table & country‑style dining",
      "description": "Michelin‑recommended restaurant offering seven‑ or ten‑course dinners, four‑course lunches and picnic baskets. Chefs Daniel Charbonneau and Yannick Côté showcase boreal ingredients and produce from their market farm Le Jardinier Déchaîné.",
      "lat": 45.3706231,
      "lng": -71.5990644,
      "mapsUrl": "https://www.google.com/maps?cid=9357413843604925008",
      "routeUrl": null,
      "rating": 4,
      "resolvedName": "Restaurant Les Mal-aimés",
      "address": "429 Rte 253, Cookshire-Eaton, Quebec J0B 1M0",
      "status": null,
      "linkLabel": "Maps"
    },
    {
      "id": "dining-parcelles-austin-maps",
      "title": "Parcelles (Austin)",
      "baseTitle": "Parcelles (Austin)",
      "category": "dining",
      "section": "Cafés, Coffee Roasteries & Lunch Spots",
      "subsection": "Farm‑to‑table & country‑style dining",
      "description": "Vegetable farm and table champêtre known for wood‑oven pizzas, natural wines and garden‑fresh crudités. Open Fridays to Sundays midday to sunset; guests dine in the fields or inside a shelter on rainy days.",
      "lat": 45.2038934,
      "lng": -72.2390176,
      "mapsUrl": "https://www.google.com/maps?cid=18203771719149802968",
      "routeUrl": null,
      "rating": 4,
      "resolvedName": "Parcelles",
      "address": "21 Chem. Taylor, Austin, QC J0B 1B0",
      "status": null,
      "linkLabel": "Maps"
    },
    {
      "id": "dining-jardins-bolton-bolton-est-maps",
      "title": "Jardins Bolton (Bolton‑Est)",
      "baseTitle": "Jardins Bolton (Bolton‑Est)",
      "category": "dining",
      "section": "Cafés, Coffee Roasteries & Lunch Spots",
      "subsection": "Farm‑to‑table & country‑style dining",
      "description": "Open‑air gastronomic evenings held on a hilltop with views of fields, mountains and a river. Guests share a large table while chefs cook over an open fire; the weekly changing menu celebrates local ingredients.",
      "lat": 45.2119846,
      "lng": -72.3551233,
      "mapsUrl": "https://www.google.com/maps?cid=7321710323086294437",
      "routeUrl": null,
      "rating": 5,
      "resolvedName": "Les Jardins Bolton",
      "address": "2 Rue Terrio, Bolton-Est, QC J0E 1G0",
      "status": null,
      "linkLabel": "Maps"
    },
    {
      "id": "experiences-spa-eastman",
      "title": "Spa Eastman",
      "baseTitle": "Spa Eastman",
      "category": "experiences",
      "section": "Other Notable Experiences",
      "subsection": "",
      "description": "One of the world’s leading spas, located in Eastman with ponds and wooded trails.",
      "lat": 45.2944,
      "lng": -72.3436,
      "mapsUrl": "https://www.google.com/maps/search/?api=1&query=Spa+Eastman+Quebec",
      "routeUrl": null,
      "rating": null,
      "resolvedName": null,
      "address": null,
      "status": null,
      "linkLabel": "Maps"
    },
    {
      "id": "experiences-missisquoi-museum-walbridge-barn",
      "title": "Missisquoi Museum & Walbridge Barn",
      "baseTitle": "Missisquoi Museum & Walbridge Barn",
      "category": "experiences",
      "section": "Other Notable Experiences",
      "subsection": "",
      "description": "Regional heritage at the Cornell Mill, Hodge’s General Store and the distinctive 12-sided Walbridge Barn in Mystic.",
      "lat": 45.1139,
      "lng": -72.9162,
      "mapsUrl": "https://www.google.com/maps/search/?api=1&query=Missisquoi+Museum+Walbridge+Barn+Stanbridge+East+Quebec",
      "routeUrl": null,
      "rating": null,
      "resolvedName": null,
      "address": null,
      "status": null,
      "linkLabel": "Maps"
    },
    {
      "id": "experiences-heritage-literary-trails-eastman",
      "title": "Heritage & Literary Trails - Eastman",
      "baseTitle": "Heritage & Literary Trails - Eastman",
      "category": "experiences",
      "section": "Other Notable Experiences",
      "subsection": "",
      "description": "Eastman’s trail around Lake d’Argent features texts by Quebec authors and local heritage stops.",
      "lat": 45.3002,
      "lng": -72.3147,
      "mapsUrl": "https://www.google.com/maps/search/?api=1&query=Eastman+heritage+literary+trail+Lake+d%27Argent+Quebec",
      "routeUrl": null,
      "rating": null,
      "resolvedName": null,
      "address": null,
      "status": null,
      "linkLabel": "Maps"
    },
    {
      "id": "experiences-frontenac-national-park",
      "title": "Frontenac National Park",
      "baseTitle": "Frontenac National Park",
      "category": "experiences",
      "section": "Other Notable Experiences",
      "subsection": "",
      "description": "Near Lambton, this park provides biking, kayaking, swimming and stargazing along Lake Saint-François.",
      "lat": 45.8526,
      "lng": -71.1965,
      "mapsUrl": "https://www.google.com/maps/search/?api=1&query=Parc+national+de+Frontenac+Quebec",
      "routeUrl": null,
      "rating": null,
      "resolvedName": null,
      "address": null,
      "status": null,
      "linkLabel": "Maps"
    }
  ]
};
